# version: "3.9"

services:
  backend:
    build: .
    container_name: dependency-risk-analyzer
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    restart: unless-stopped 
  
#   ollama:
#     image: ollama/ollama:latest
#     container_name: ollama
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama-data:/root/ .ollama
#     healthcheck:
#       test: ["CMD", "ollama", "list"]
#       interval: 15s
#       timeout: 5s
#       retries: 10
#     restart: unless-stopped

# volumes:
#   ollama-data: